### ISSUE TITLE
julia_lineprofiler no working

### ISSUE THREAD

**Issue by vkuehn** [mynameisfiber/high_performance_python#11]
the example scripts for julia_lineprfiler do not work

thought this does not work in any python version
`
    print "Length of x:", len(x)    

    print "Total elements:", len(zs)
`

@profile decorator is not explained completely as once added the script can not be called with kernprof

**Comment by ianozsvald** [comment]
You're looking at the 1st edition of the book's code for Python 2.7. You'll
find updated code on the 2nd edition repository, released last year on
Python 3.7+:
https://github.com/mynameisfiber/high_performance_python_2e
Regards Ian

**Comment by vkuehn** [comment]
oh ok ...thanks for that
