### ISSUE TITLE
Recent version of kernprof fails with exception(s)

### ISSUE THREAD

**Issue by cans** [mynameisfiber/high_performance_python#8]
There are 2 issues:

- print statements syntax no longer support (with either Python 2 or 3);
- Functions have no longer have a `func_name` attribute;

**Comment by mynameisfiber** [comment]
@cans You are correct about these things for python3, but they haven't changed in python2. In general, this codebase is python2 specific. While the code itself doesn't run in python3, the theory should be transferable.
